\set ON_ERROR_STOP
\set ECHO all
BEGIN;
\set ECHO all
CREATE SEQUENCE "transfers"."agents_id_seq" INCREMENT BY 1 START WITH 1 OWNED BY "transfers"."agents"."id";
CREATE SEQUENCE "transfers"."awards_id_seq" INCREMENT BY 1 START WITH 1 OWNED BY "transfers"."awards"."id";
CREATE SEQUENCE "transfers"."clubs_id_seq" INCREMENT BY 1 START WITH 1 OWNED BY "transfers"."clubs"."id";
CREATE SEQUENCE "transfers"."coaches_id_seq" INCREMENT BY 1 START WITH 1 OWNED BY "transfers"."coaches"."id";
CREATE SEQUENCE "transfers"."leagues_id_seq" INCREMENT BY 1 START WITH 1 OWNED BY "transfers"."leagues"."id";
CREATE SEQUENCE "transfers"."leagueseasons_id_seq" INCREMENT BY 1 START WITH 1 OWNED BY "transfers"."leagueseasons"."id";
CREATE SEQUENCE "transfers"."nationalities_id_seq" INCREMENT BY 1 START WITH 1 OWNED BY "transfers"."nationalities"."id";
CREATE SEQUENCE "transfers"."player_agents_id_seq" INCREMENT BY 1 START WITH 1 OWNED BY "transfers"."player_agents"."id";
CREATE SEQUENCE "transfers"."player_awards_id_seq" INCREMENT BY 1 START WITH 1 OWNED BY "transfers"."player_awards"."id";
CREATE SEQUENCE "transfers"."players_id_seq" INCREMENT BY 1 START WITH 1 OWNED BY "transfers"."players"."id";
CREATE SEQUENCE "transfers"."positions_id_seq" INCREMENT BY 1 START WITH 1 OWNED BY "transfers"."positions"."id";
CREATE SEQUENCE "transfers"."preffered_foot_id_seq" INCREMENT BY 1 START WITH 1 OWNED BY "transfers"."preffered_foot"."id";
CREATE SEQUENCE "transfers"."stats_id_seq" INCREMENT BY 1 START WITH 1 OWNED BY "transfers"."stats"."id";
CREATE SEQUENCE "transfers"."transfers_id_seq" INCREMENT BY 1 START WITH 1 OWNED BY "transfers"."transfers"."id";
ALTER TABLE "transfers"."agents" ADD PRIMARY KEY ("id");
ALTER TABLE "transfers"."awards" ADD PRIMARY KEY ("id");
ALTER TABLE "transfers"."clubs" ADD PRIMARY KEY ("id");
ALTER TABLE "transfers"."coaches" ADD PRIMARY KEY ("id");
ALTER TABLE "transfers"."leagues" ADD PRIMARY KEY ("id");
ALTER TABLE "transfers"."leagueseasons" ADD PRIMARY KEY ("id");
ALTER TABLE "transfers"."nationalities" ADD PRIMARY KEY ("id");
ALTER TABLE "transfers"."players" ADD PRIMARY KEY ("id");
ALTER TABLE "transfers"."player_agents" ADD PRIMARY KEY ("id");
ALTER TABLE "transfers"."player_awards" ADD PRIMARY KEY ("id");
ALTER TABLE "transfers"."positions" ADD PRIMARY KEY ("id");
ALTER TABLE "transfers"."preffered_foot" ADD PRIMARY KEY ("id");
ALTER TABLE "transfers"."stats" ADD PRIMARY KEY ("id");
ALTER TABLE "transfers"."transfers" ADD PRIMARY KEY ("id");
CREATE INDEX "ix_agents_last_name" ON "transfers"."agents" ("last_name" ASC);
CREATE INDEX "ix_agents_last_name_first_name" ON "transfers"."agents" ("last_name" ASC,"first_name" ASC);
CREATE INDEX "ix_clubs_coach_id" ON "transfers"."clubs" ("coach_id" ASC);
CREATE INDEX "ix_clubs_league_id" ON "transfers"."clubs" ("league_id" ASC);
CREATE INDEX "ix_clubs_name" ON "transfers"."clubs" ("name" ASC);
CREATE INDEX "ix_coaches_last_name" ON "transfers"."coaches" ("last_name" ASC);
CREATE INDEX "ix_coaches_last_name_first_name" ON "transfers"."coaches" ("last_name" ASC,"first_name" ASC);
CREATE INDEX "ix_leagueseasons_league_id" ON "transfers"."leagueseasons" ("league_id" ASC);
CREATE INDEX "ix_players_current_club_id" ON "transfers"."players" ("current_club_id" ASC);
CREATE INDEX "ix_players_last_name" ON "transfers"."players" ("last_name" ASC);
CREATE INDEX "ix_players_last_name_first_name" ON "transfers"."players" ("last_name" ASC,"first_name" ASC);
CREATE INDEX "ix_players_market_value" ON "transfers"."players" ("market_value" DESC);
CREATE INDEX "ix_playeragents_agent_id" ON "transfers"."player_agents" ("agent_id" ASC);
CREATE INDEX "ix_playeragents_player_id" ON "transfers"."player_agents" ("player_id" ASC);
CREATE INDEX "ix_playerawards_award_id" ON "transfers"."player_awards" ("award_id" ASC);
CREATE INDEX "ix_playerawards_player_id" ON "transfers"."player_awards" ("player_id" ASC);
CREATE INDEX "ix_statistics_league_season_id" ON "transfers"."stats" ("league_season_id" ASC);
CREATE INDEX "ix_statistics_player_id" ON "transfers"."stats" ("player_id" ASC);
CREATE INDEX "ix_transfers_player_id" ON "transfers"."transfers" ("player_id" ASC);
CREATE INDEX "ix_transfers_transfer_date" ON "transfers"."transfers" ("transfer_date" DESC);
ALTER TABLE "transfers"."clubs" ADD CONSTRAINT "fk_clubs_coaches" FOREIGN KEY ("coach_id") REFERENCES "transfers"."coaches" ( "id");
ALTER TABLE "transfers"."clubs" ADD CONSTRAINT "fk_clubs_leagues" FOREIGN KEY ("league_id") REFERENCES "transfers"."leagues" ( "id");
ALTER TABLE "transfers"."clubs" ADD CONSTRAINT "fk_clubs_nationalities" FOREIGN KEY ("country_id") REFERENCES "transfers"."nationalities" ( "id");
ALTER TABLE "transfers"."coaches" ADD CONSTRAINT "fk_coaches_nationalities" FOREIGN KEY ("nationality_id") REFERENCES "transfers"."nationalities" ( "id");
ALTER TABLE "transfers"."leagues" ADD CONSTRAINT "fk_leagues_nationalities" FOREIGN KEY ("country_id") REFERENCES "transfers"."nationalities" ( "id");
ALTER TABLE "transfers"."leagueseasons" ADD CONSTRAINT "fk_leagueseasons_leagues" FOREIGN KEY ("league_id") REFERENCES "transfers"."leagues" ( "id");
ALTER TABLE "transfers"."players" ADD CONSTRAINT "fk_players_clubs" FOREIGN KEY ("current_club_id") REFERENCES "transfers"."clubs" ( "id");
ALTER TABLE "transfers"."players" ADD CONSTRAINT "fk_players_nationalities" FOREIGN KEY ("nationality_id") REFERENCES "transfers"."nationalities" ( "id");
ALTER TABLE "transfers"."players" ADD CONSTRAINT "fk_players_positions" FOREIGN KEY ("position_id") REFERENCES "transfers"."positions" ( "id");
ALTER TABLE "transfers"."players" ADD CONSTRAINT "fk_players_preferredfoot" FOREIGN KEY ("preferred_foot_id") REFERENCES "transfers"."preffered_foot" ( "id");
ALTER TABLE "transfers"."player_agents" ADD CONSTRAINT "fk_playeragents_agents" FOREIGN KEY ("agent_id") REFERENCES "transfers"."agents" ( "id");
ALTER TABLE "transfers"."player_agents" ADD CONSTRAINT "fk_playeragents_players" FOREIGN KEY ("player_id") REFERENCES "transfers"."players" ( "id");
ALTER TABLE "transfers"."player_awards" ADD CONSTRAINT "fk_playerawards_awards" FOREIGN KEY ("award_id") REFERENCES "transfers"."awards" ( "id");
ALTER TABLE "transfers"."player_awards" ADD CONSTRAINT "fk_playerawards_players" FOREIGN KEY ("player_id") REFERENCES "transfers"."players" ( "id");
ALTER TABLE "transfers"."stats" ADD CONSTRAINT "fk_statistics_clubs" FOREIGN KEY ("club_id") REFERENCES "transfers"."clubs" ( "id");
ALTER TABLE "transfers"."stats" ADD CONSTRAINT "fk_statistics_leagueseasons" FOREIGN KEY ("league_season_id") REFERENCES "transfers"."leagueseasons" ( "id");
ALTER TABLE "transfers"."stats" ADD CONSTRAINT "fk_statistics_players" FOREIGN KEY ("player_id") REFERENCES "transfers"."players" ( "id");
ALTER TABLE "transfers"."transfers" ADD CONSTRAINT "fk_transfers_fromclub" FOREIGN KEY ("from_club_id") REFERENCES "transfers"."clubs" ( "id");
ALTER TABLE "transfers"."transfers" ADD CONSTRAINT "fk_transfers_players" FOREIGN KEY ("player_id") REFERENCES "transfers"."players" ( "id");
ALTER TABLE "transfers"."transfers" ADD CONSTRAINT "fk_transfers_toclub" FOREIGN KEY ("to_club_id") REFERENCES "transfers"."clubs" ( "id");
ALTER TABLE "transfers"."agents" ALTER COLUMN "id" SET DEFAULT nextval('"transfers"."agents_id_seq"');
ALTER TABLE "transfers"."awards" ALTER COLUMN "id" SET DEFAULT nextval('"transfers"."awards_id_seq"');
ALTER TABLE "transfers"."clubs" ALTER COLUMN "id" SET DEFAULT nextval('"transfers"."clubs_id_seq"');
ALTER TABLE "transfers"."coaches" ALTER COLUMN "id" SET DEFAULT nextval('"transfers"."coaches_id_seq"');
ALTER TABLE "transfers"."leagues" ALTER COLUMN "id" SET DEFAULT nextval('"transfers"."leagues_id_seq"');
ALTER TABLE "transfers"."leagueseasons" ALTER COLUMN "id" SET DEFAULT nextval('"transfers"."leagueseasons_id_seq"');
ALTER TABLE "transfers"."nationalities" ALTER COLUMN "id" SET DEFAULT nextval('"transfers"."nationalities_id_seq"');
ALTER TABLE "transfers"."players" ALTER COLUMN "id" SET DEFAULT nextval('"transfers"."players_id_seq"');
ALTER TABLE "transfers"."player_agents" ALTER COLUMN "id" SET DEFAULT nextval('"transfers"."player_agents_id_seq"');
ALTER TABLE "transfers"."player_awards" ALTER COLUMN "id" SET DEFAULT nextval('"transfers"."player_awards_id_seq"');
ALTER TABLE "transfers"."positions" ALTER COLUMN "id" SET DEFAULT nextval('"transfers"."positions_id_seq"');
ALTER TABLE "transfers"."preffered_foot" ALTER COLUMN "id" SET DEFAULT nextval('"transfers"."preffered_foot_id_seq"');
ALTER TABLE "transfers"."stats" ALTER COLUMN "appearances" SET DEFAULT 0;
ALTER TABLE "transfers"."stats" ALTER COLUMN "assists" SET DEFAULT 0;
ALTER TABLE "transfers"."stats" ALTER COLUMN "goals" SET DEFAULT 0;
ALTER TABLE "transfers"."stats" ALTER COLUMN "id" SET DEFAULT nextval('"transfers"."stats_id_seq"');
ALTER TABLE "transfers"."stats" ALTER COLUMN "minutes_played" SET DEFAULT 0;
ALTER TABLE "transfers"."stats" ALTER COLUMN "red_cards" SET DEFAULT 0;
ALTER TABLE "transfers"."stats" ALTER COLUMN "yellow_cards" SET DEFAULT 0;
ALTER TABLE "transfers"."transfers" ALTER COLUMN "id" SET DEFAULT nextval('"transfers"."transfers_id_seq"');
COMMIT;
